### ISSUE TITLE
Working directory configuration

### ISSUE THREAD

**Issue by pauldaustin** [Azure/bicep-build-action#2]
Can you provide an example of specifying a working-directory for this action? Or if is not supported can you add this functionality?

I tried the following and it fails. This would be the same as how it would be specified for say the run action.

```yaml
    - name: Azure Template Build
      uses: Azure/bicep-build-action@v1.0.0
      with:
        bicepFilePath: AppServer.bicep
        outputFilePath: AppServer.json
      working-directory: ./arm/AppServer
```
